In [26]:
import numpy as np 
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
import warnings
warnings.filterwarnings('ignore')

from sklearn import neighbors
from sklearn.model_selection import cross_val_score,train_test_split


In [6]:
iris = datasets.load_iris()
X = iris.data[:, :2]
y = iris.target

In [8]:
X[0]

array([5.1, 3.5])

In [9]:
y[0]

0

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [30]:
knn = neighbors.KNeighborsClassifier(3)

In [31]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [32]:
y_predict = knn.predict(X_test)

In [33]:
y_predict

array([1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 2, 0, 1, 0,
       0, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 0, 2, 1, 1, 2])

In [34]:
from sklearn.metrics import confusion_matrix 
confusion_matrix(y_test, y_predict)

array([[11,  0,  0],
       [ 0, 10,  1],
       [ 0, 10,  6]], dtype=int64)

In [35]:
knn.score(X_test,y_test)

0.7105263157894737